--
-- PostgreSQL database dump
--

\restrict kEa93YwVwguKvvbL2HL3za1eMTQUXvx0dz6KGJPiWOobfVcUsa9yfSyJiP8wc7j

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: assignment; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.assignment (
    confirmed boolean,
    employee_id bigint,
    id bigint NOT NULL,
    role_id bigint,
    shift_id bigint
);


ALTER TABLE public.assignment OWNER TO demo;

--
-- Name: assignment_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.assignment_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.assignment_seq OWNER TO demo;

--
-- Name: company; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    company_name character varying(255)
);


ALTER TABLE public.company OWNER TO demo;

--
-- Name: company_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.company_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.company_seq OWNER TO demo;

--
-- Name: employee; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.employee (
    birthdate date,
    hourly_wage double precision,
    is_manager boolean,
    company_id bigint,
    id bigint NOT NULL,
    address character varying(255),
    email character varying(255),
    firstname character varying(255),
    keycloak_user_id character varying(255),
    lastname character varying(255),
    telephone character varying(255)
);


ALTER TABLE public.employee OWNER TO demo;

--
-- Name: employee_role; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.employee_role (
    employee_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.employee_role OWNER TO demo;

--
-- Name: employee_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.employee_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.employee_seq OWNER TO demo;

--
-- Name: manager; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.manager (
    birthdate timestamp(6) without time zone,
    company_id bigint,
    id bigint NOT NULL,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password character varying(255),
    telephone character varying(255)
);


ALTER TABLE public.manager OWNER TO demo;

--
-- Name: manager_id_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

ALTER TABLE public.manager ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.manager_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.news (
    assignment_status boolean,
    assignment_id bigint NOT NULL,
    company_id bigint,
    date_created timestamp(6) without time zone,
    id bigint NOT NULL
);


ALTER TABLE public.news OWNER TO demo;

--
-- Name: news_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.news_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.news_seq OWNER TO demo;

--
-- Name: reservation; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.reservation (
    endtime time(6) without time zone,
    numberofpeople integer NOT NULL,
    starttime time(6) without time zone,
    id bigint NOT NULL,
    shift_id bigint,
    infos character varying(255),
    name character varying(255)
);


ALTER TABLE public.reservation OWNER TO demo;

--
-- Name: reservation_id_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

ALTER TABLE public.reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.role (
    company_id bigint,
    id bigint NOT NULL,
    description character varying(255),
    role_name character varying(255)
);


ALTER TABLE public.role OWNER TO demo;

--
-- Name: role_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.role_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.role_seq OWNER TO demo;

--
-- Name: shift; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.shift (
    company_id bigint,
    end_time timestamp(6) without time zone,
    id bigint NOT NULL,
    start_time timestamp(6) without time zone,
    shift_name character varying(255)
);


ALTER TABLE public.shift OWNER TO demo;

--
-- Name: shift_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.shift_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.shift_seq OWNER TO demo;

--
-- Name: shift_template; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.shift_template (
    company_id bigint,
    id bigint NOT NULL,
    shift_template_name character varying(255)
);


ALTER TABLE public.shift_template OWNER TO demo;

--
-- Name: shift_template_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.shift_template_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.shift_template_seq OWNER TO demo;

--
-- Name: template_role; Type: TABLE; Schema: public; Owner: demo
--

CREATE TABLE public.template_role (
    count integer,
    id bigint NOT NULL,
    role_id bigint,
    shift_template_id bigint
);


ALTER TABLE public.template_role OWNER TO demo;

--
-- Name: template_role_seq; Type: SEQUENCE; Schema: public; Owner: demo
--

CREATE SEQUENCE public.template_role_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.template_role_seq OWNER TO demo;

--
-- Data for Name: assignment; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.assignment (confirmed, employee_id, id, role_id, shift_id) FROM stdin;
\N	1	1	1	1
\N	1	2	1	2
\N	1	3	1	5
\N	3	4	1	3
\N	3	5	1	4
\N	4	6	1	4
\N	4	7	2	5
\N	5	8	2	5
\N	4	12	3	5
\N	5	13	3	5
\N	6	14	3	5
\N	1	15	1	5
\N	3	17	3	5
\N	4	18	3	6
\N	5	19	3	6
\N	6	20	3	6
\N	1	21	1	6
\N	2	22	3	6
\N	3	23	3	6
\N	4	24	3	7
\N	5	25	3	7
\N	6	26	3	7
\N	1	27	1	7
\N	2	28	3	7
\N	3	29	3	7
\N	4	30	3	8
\N	5	31	3	8
\N	6	32	3	8
\N	1	33	1	8
\N	3	35	3	8
t	2	34	2	8
f	2	11	2	9
t	2	16	3	5
f	2	9	2	3
t	2	10	2	5
\.


--
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.company (id, company_name) FROM stdin;
1	Stoaboch Wirt
\.


--
-- Data for Name: employee; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.employee (birthdate, hourly_wage, is_manager, company_id, id, address, email, firstname, keycloak_user_id, lastname, telephone) FROM stdin;
2004-11-11	10	f	1	1	Limesstraße 12, 4060 Leonding	p.pfarrhofer@students.htl-leonding.ac.at	john	49edbca3-c26a-43b1-ba13-9fcab951cbe9	doe	1233456899
2001-11-09	20	f	1	2	Limesstraße 12, 4060 Leonding	alexander.hahn1@outlook.de	Alexander	a1329681-9ac4-4627-a7d6-d29527a540b2	Hahn	65626625
2006-11-11	10	f	1	3	Limesstraße 12, 4060 Leonding	o.ffen@students.htl-leonding.ac.at	offen	56927d41-566c-4841-a12f-339e087777a5		1233456899
1975-02-27	10	t	1	4	Limesstraße 12, 4060 Leonding	bernhard@penkner.com	Bernhard	96257644-5ebc-4a07-a9ce-27251df492ab	Penkner	67734144524
1995-03-22	10	f	1	5	Limesstraße 12, 4060 Leonding	michael.brown@example.com	Michael	62542725-78d7-4100-87fa-7c1844aad9e5	Brown	5551234567
1992-08-17	10	f	1	6	Limesstraße 12, 4060 Leonding	sarah.jones@example.com	Sarah	15111cdd-afb2-46be-a605-4c72f61af41a	Jones	4441239876
1988-12-01	10	f	1	7	Limesstraße 12, 4060 Leonding	daniel.white@example.com	Daniel	70469962-4b01-4701-93dd-11856e3cc1d1	White	6669876543
\.


--
-- Data for Name: employee_role; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.employee_role (employee_id, role_id) FROM stdin;
1	1
1	3
2	2
2	3
3	3
3	4
3	1
4	4
5	3
\.


--
-- Data for Name: manager; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.manager (birthdate, company_id, id, email, firstname, lastname, password, telephone) FROM stdin;
2000-11-20 00:00:00	1	1	bernhard@penkner.com	Bernhard	Penkner	\N	+43677238384878
\.


--
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.news (assignment_status, assignment_id, company_id, date_created, id) FROM stdin;
\.


--
-- Data for Name: reservation; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.reservation (endtime, numberofpeople, starttime, id, shift_id, infos, name) FROM stdin;
17:00:00	120	13:00:00	1	1	Die Loisi feiert ihren 60er.	Geburtstag Loisi
13:30:00	4	12:00:00	2	1		Reservierung Riener
\.


--
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.role (company_id, id, description, role_name) FROM stdin;
1	1	Ist verantwortlich für die Küche und kocht das Essen	Koch
1	2	Unterstützt den Koch in der Küche	Küchenhilfe
1	3	Ist für den Service der Gäste verantwortlich	Kellner
1	4	Serviert (anti-)akoholische Getränke an der Bar	Barkeeper
1	5	Reinigt und sortiert das Geschirr	Spülkraft
\.


--
-- Data for Name: shift; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.shift (company_id, end_time, id, start_time, shift_name) FROM stdin;
1	2026-03-13 17:00:00	1	2026-03-13 09:00:00	Mittagsschicht
1	2026-03-13 20:00:00	2	2026-03-13 18:00:00	Abendschicht
1	2026-03-26 16:00:00	3	2026-03-26 08:00:00	Mittags Schicht
1	2026-03-27 22:00:00	4	2026-03-27 14:00:00	Abend Schicht
1	2026-03-28 18:00:00	5	2026-03-28 10:00:00	Mittags Schicht
1	2026-03-14 17:00:00	6	2026-03-14 09:00:00	Abend Schicht
1	2026-03-15 19:00:00	7	2026-03-15 11:00:00	Mittags Schicht
1	2026-03-17 16:00:00	8	2026-03-17 08:00:00	Abend Schicht
1	2026-03-18 20:00:00	9	2026-03-18 12:00:00	Nachmittags Schicht
1	2026-03-19 20:00:00	10	2026-03-19 12:00:00	Nachmittags Schicht
1	2026-03-20 23:00:00	11	2026-03-20 20:00:00	Abend Schicht
\.


--
-- Data for Name: shift_template; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.shift_template (company_id, id, shift_template_name) FROM stdin;
1	1	Sonntags Schicht
1	2	Mittags Schicht
1	3	Abend Schicht
\.


--
-- Data for Name: template_role; Type: TABLE DATA; Schema: public; Owner: demo
--

COPY public.template_role (count, id, role_id, shift_template_id) FROM stdin;
3	1	1	1
1	2	2	1
2	3	3	1
1	4	1	2
2	5	2	2
1	6	3	2
3	7	1	3
3	8	2	3
2	9	3	3
\.


--
-- Name: assignment_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.assignment_seq', 36, false);


--
-- Name: company_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.company_seq', 2, false);


--
-- Name: employee_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.employee_seq', 8, false);


--
-- Name: manager_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.manager_id_seq', 1, true);


--
-- Name: news_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.news_seq', 1, false);


--
-- Name: reservation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.reservation_id_seq', 2, true);


--
-- Name: role_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.role_seq', 6, false);


--
-- Name: shift_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.shift_seq', 12, false);


--
-- Name: shift_template_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.shift_template_seq', 4, false);


--
-- Name: template_role_seq; Type: SEQUENCE SET; Schema: public; Owner: demo
--

SELECT pg_catalog.setval('public.template_role_seq', 10, false);


--
-- Name: assignment assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.assignment
    ADD CONSTRAINT assignment_pkey PRIMARY KEY (id);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: employee employee_email_key; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_email_key UNIQUE (email);


--
-- Name: employee employee_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT employee_pkey PRIMARY KEY (id);


--
-- Name: manager manager_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.manager
    ADD CONSTRAINT manager_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: reservation reservation_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.reservation
    ADD CONSTRAINT reservation_pkey PRIMARY KEY (id);


--
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- Name: shift shift_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.shift
    ADD CONSTRAINT shift_pkey PRIMARY KEY (id);


--
-- Name: shift_template shift_template_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.shift_template
    ADD CONSTRAINT shift_template_pkey PRIMARY KEY (id);


--
-- Name: template_role template_role_pkey; Type: CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.template_role
    ADD CONSTRAINT template_role_pkey PRIMARY KEY (id);


--
-- Name: assignment fk4wua053vxx2md0lguxn76r8sx; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.assignment
    ADD CONSTRAINT fk4wua053vxx2md0lguxn76r8sx FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: assignment fk55w02ia8o95vsxfgetm0yp0rv; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.assignment
    ADD CONSTRAINT fk55w02ia8o95vsxfgetm0yp0rv FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: news fk6gda3lon8w53demuy11x747p3; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT fk6gda3lon8w53demuy11x747p3 FOREIGN KEY (assignment_id) REFERENCES public.assignment(id) ON DELETE CASCADE;


--
-- Name: template_role fk74mkuc6phsv56sl9puem5dpb0; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.template_role
    ADD CONSTRAINT fk74mkuc6phsv56sl9puem5dpb0 FOREIGN KEY (shift_template_id) REFERENCES public.shift_template(id);


--
-- Name: employee_role fkc7raan3p2ya4ii6s2gpa1sl3e; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.employee_role
    ADD CONSTRAINT fkc7raan3p2ya4ii6s2gpa1sl3e FOREIGN KEY (employee_id) REFERENCES public.employee(id);


--
-- Name: shift fket4hi8eit92vwuhaj3c6bhy5m; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.shift
    ADD CONSTRAINT fket4hi8eit92vwuhaj3c6bhy5m FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: assignment fkfwcihwge3sae0mw7m62k301v9; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.assignment
    ADD CONSTRAINT fkfwcihwge3sae0mw7m62k301v9 FOREIGN KEY (shift_id) REFERENCES public.shift(id);


--
-- Name: template_role fkg4pft5uilkp9k1e3rbfqccxt8; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.template_role
    ADD CONSTRAINT fkg4pft5uilkp9k1e3rbfqccxt8 FOREIGN KEY (role_id) REFERENCES public.role(id) ON DELETE CASCADE;


--
-- Name: shift_template fkgmd8ved67rh35k5snu11llb5w; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.shift_template
    ADD CONSTRAINT fkgmd8ved67rh35k5snu11llb5w FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: news fkgwl0vopofql3ivujdgy32rfs; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT fkgwl0vopofql3ivujdgy32rfs FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: employee_role fkn9cxwmunt7nmoa37y4iql6x94; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.employee_role
    ADD CONSTRAINT fkn9cxwmunt7nmoa37y4iql6x94 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- Name: employee fkogydjhdlcl557ppjr3g8xwmh0; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.employee
    ADD CONSTRAINT fkogydjhdlcl557ppjr3g8xwmh0 FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- Name: role fkqbkpka79wedf5x3y3njhv7jhf; Type: FK CONSTRAINT; Schema: public; Owner: demo
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT fkqbkpka79wedf5x3y3njhv7jhf FOREIGN KEY (company_id) REFERENCES public.company(id);


--
-- PostgreSQL database dump complete
--

\unrestrict kEa93YwVwguKvvbL2HL3za1eMTQUXvx0dz6KGJPiWOobfVcUsa9yfSyJiP8wc7j

