export enum AssignmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
  REQUESTED = 'REQUESTED',
  REQUEST_CONFIRMED = 'REQUEST_CONFIRMED',
  REQUEST_DECLINED = 'REQUEST_DECLINED'
}
