### Get access token (client credentials)
POST http://localhost:8081/realms/demo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id=backend&
client_secret=backend-secret-instaff

> {% client.global.set("access_token", response.body.access_token); %}

### Get access token (password)
POST http://localhost:8081/realms/demo/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&
client_id=frontend&
client_secret=backend-secret-instaff&
username=bernhard@penkner.com&
password=admin

> {% client.global.set("access_token", response.body.access_token); %}

###############################################
# EMPLOYEE
###############################################

### Get all employees
GET http://localhost:8080/api/employees
Authorization: Bearer {{access_token}}

###

### Get employee by ID
GET http://localhost:8080/api/employees/2
Authorization: Bearer {{access_token}}

###

### Get employee by Keycloak ID
GET http://localhost:8080/api/employees/keycloak/a1329681-9ac4-4627-a7d6-d29527a540b2
Authorization: Bearer {{access_token}}

###

### Get employees by role ID
GET http://localhost:8080/api/employees/role/1
Authorization: Bearer {{access_token}}

###

### Get employees by partial name
GET http://localhost:8080/api/employees/name/White Dan
Authorization: Bearer {{access_token}}

###

### Create new employee
POST http://localhost:8080/api/employees
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Smith",
  "email": "john.smith@example.com",
  "telephone": "+43 987 654321",
  "password": "securePassword123",
  "birthdate": "1990-01-01",
  "isManager": false,
  "roles": [1, 2],
  "hourlyWage": 12.5,
  "address": "Example Street 123"
}

###

### Update employee
PUT http://localhost:8080/api/employees/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "firstname": "Jane",
  "lastname": "Doe",
  "email": "jane.doe@example.com",
  "birthdate": "1992-05-14",
  "telephone": "+43 123 456789",
  "isManager": true,
  "roles": [1, 2],
  "hourlyWage": 14.5,
  "address": "Musterstrasse 12"
}

### Update alexander hahn
PUT http://localhost:8080/api/employees/2
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "firstname": "Alexander",
  "lastname": "Hahn",
  "email": "a.hahn@example.com",
  "birthdate": "2001-11-09",
  "telephone": "65626625",
  "isManager": false,
  "roles": [2, 3],
  "hourlyWage": 20.0,
  "address": "Limesstraße 12, 4060 Leonding"
}

###

### Delete employee by ID
DELETE http://localhost:8080/api/employees/1
Authorization: Bearer {{access_token}}

###

### Assign role to employee
PUT http://localhost:8080/api/employees/3/assignrole/2
Authorization: Bearer {{access_token}}

###

### Remove role from employee
PUT http://localhost:8080/api/employees/3/removerole/2
Authorization: Bearer {{access_token}}


###############################################
# ROLES
###############################################

### Get all roles
GET http://localhost:8080/api/roles
Authorization: Bearer {{access_token}}

###

### Get role by ID
GET http://localhost:8080/api/roles/1
Authorization: Bearer {{access_token}}

###

### Create new role
POST http://localhost:8080/api/roles
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roleName": "Supervisor",
  "description": "Supervises the shift"
}

###

### Update role
PUT http://localhost:8080/api/roles/1
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "roleName": "Chef",
  "description": "Cooks"
}

###

### Delete role by ID
DELETE http://localhost:8080/api/roles/1
Authorization: Bearer {{access_token}}


###############################################
# ASSIGNMENTS
###############################################

### Create new Assignment
POST http://localhost:8080/api/assignments
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "employeeId": 1,
  "shiftId": 1,
  "roleId": 1
}

###

### Delete Assignment
DELETE http://localhost:8080/api/assignments/1
Authorization: Bearer {{access_token}}

###

### Get all assignments
GET http://localhost:8080/api/assignments
Authorization: Bearer {{access_token}}

###

### Get assignment by ID
GET http://localhost:8080/api/assignments/1
Authorization: Bearer {{access_token}}

###

### Get assignments by shift ID
GET http://localhost:8080/api/assignments/shift/1
Authorization: Bearer {{access_token}}

###

### Get assignments by employee ID
GET http://localhost:8080/api/assignments/employee/2
Authorization: Bearer {{access_token}}

###

### Get assignments by employee ID between dates
GET http://localhost:8080/api/assignments/employee/1/2025-03-24/2025-03-27

###

### Confirm assignment
PUT http://localhost:8080/api/assignments/30/confirm/true
Authorization: Bearer {{access_token}}

###

### Decline assignment
PUT http://localhost:8080/api/assignments/30/confirm/false
Authorization: Bearer {{access_token}}


###############################################
# SHIFTS
###############################################

### Get all shifts
GET http://localhost:8080/api/shifts
Authorization: Bearer {{access_token}}

###

### Get shift by ID
GET http://localhost:8080/api/shifts/1
Authorization: Bearer {{access_token}}

###

### Get shifts by date
GET http://localhost:8080/api/shifts/date/2026-03-13
Authorization: Bearer {{access_token}}

###

### Get shifts between dates
GET http://localhost:8080/api/shifts/betweendates/2026-03-13/2026-03-27
Authorization: Bearer {{access_token}}

###

### Create new shift
POST http://localhost:8080/api/shifts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shiftName": "Test Shift",
  "startTime": "2026-03-20T06:00:00",
  "endTime": "2026-03-20T14:00:00"
}

###

### Create shift with assignments
POST http://localhost:8080/api/shifts/create-with-assignments
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shiftCreateDTO": {
    "shiftName": "Test Shift",
    "startTime": "2026-03-20T06:00:00",
    "endTime": "2026-03-20T14:00:00"
  },
  "assignmentCreateDTOS": [
    {
      "employeeId": 1,
      "roleId": 1
    }
  ]
}

###

### Delete shift by ID
DELETE http://localhost:8080/api/shifts/1
Authorization: Bearer {{access_token}}


###############################################
# SHIFT TEMPLATES
###############################################

### Get all shift templates
GET http://localhost:8080/api/shift-templates
Authorization: Bearer {{access_token}}

###

### Create new shift template
POST http://localhost:8080/api/shift-templates
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shiftTemplateName": "Standard Morning",
  "templateRoles": [
    {
      "roleId": 1,
      "count": 2
    }
  ]
}

###

### Update shift template
PUT http://localhost:8080/api/shift-templates/4
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "shiftTemplateName": "Updated Morning Template",
  "templateRoles": [
    {
      "roleId": 1,
      "count": 3
    },
    {
      "roleId": 2,
      "count": 1
    }
  ]
}

###

### Delete shift template by ID
DELETE http://localhost:8080/api/shift-templates/1
Authorization: Bearer {{access_token}}
